# Release configuration for nix-rust-template
# Only process the shared library package

[workspace]
allow_dirty = true # allow updating repositories with uncommitted changes

[[package]]
name = "nix-rust-template"
changelog_update = true # enable changelog update
publish = false


[[package]]
name = "nix-rust-template-client"
publish = false

[changelog]
protect_breaking_commits = true # always include commits with breaking changes in the changelog
