# Release configuration for nix-rust-template
# Only process the shared library package

[workspace]
allow_dirty = true # allow updating repositories with uncommitted changes

[[package]]
name = "nix-rust-template-shared"
changelog_update = true # enable changelog update
git_release_enable = true # enable GitHub/Gitea releases
publish = false # disable `cargo publish` - this is a template project

[changelog]
protect_breaking_commits = true # always include commits with breaking changes in the changelog
