[workspace]
resolver = "2"
members = [
  "shared",
  "client",
  "web",
  "server",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
description = "A rust and nix template repository."
repository = "github.com/ocasazza/crane-template"
license = "MIT"

[workspace.metadata.crane]
name = "crane-template"
version = "0.0.1"
