[workspace]
resolver = "2"
members = [
  "shared",
  "client",
  "web",
  "server",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
description = "A rust and nix template repository."
repository = "github.com/ocasazza/crane-template"
license = "MIT"
authors = ["Olive Casazza <olive.casazza@schrodinger.com>"]
name = "graph_generation_language"
homepage = "https://ocasazza.github.io/nix-rust-template/"
documentation = "https://ocasazza.github.io/nix-rust-template/"
readme = "README.md"
keywords = ["nix", "wasm", "javascript", "typescript"]

[workspace.metadata.crane]
name = "nix-rust-template"
version = "0.0.1"
