[package]
name = "nix_rust_template-web"
version.workspace = true
edition.workspace = true
license.workspace = true


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nix_rust_template = { path = "../shared" }
wasm-bindgen = "0.2"
