[package]
name = "web"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
shared = { version = "0.0.1", path = "../shared" }
wasm-bindgen = "0.2"
