[package]
name = "nix-rust-template-web"
version.workspace = true
edition.workspace = true
license.workspace = true


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nix-rust-template = { path = "../shared" }
wasm-bindgen = "0.2"
